package apex.stellar.aldebaran.controller;

import static org.hamcrest.Matchers.hasSize;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import apex.stellar.aldebaran.config.BaseIntegrationTest;
import apex.stellar.aldebaran.dto.WodMovementRequest;
import apex.stellar.aldebaran.dto.WodRequest;
import apex.stellar.aldebaran.model.entities.Movement;
import apex.stellar.aldebaran.model.entities.Wod;
import apex.stellar.aldebaran.model.entities.Wod.ScoreType;
import apex.stellar.aldebaran.model.entities.Wod.WodType;
import apex.stellar.aldebaran.model.enums.Category;
import apex.stellar.aldebaran.repository.MovementRepository;
import apex.stellar.aldebaran.repository.WodRepository;
import java.util.Collections;
import java.util.List;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.connection.RedisConnection;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.http.MediaType;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;
import tools.jackson.databind.json.JsonMapper;

/**
 * Integration tests for {@link WodController}.
 *
 * <p>Verifies the API contract, database persistence, cache interactions, and security rules using
 * real infrastructure (Testcontainers).
 */
class WodControllerIT extends BaseIntegrationTest {

  @Autowired private MockMvc mockMvc;
  @Autowired private JsonMapper objectMapper;
  @Autowired private WodRepository wodRepository;
  @Autowired private MovementRepository movementRepository;

  @Autowired private StringRedisTemplate redisTemplate;

  private Movement pullUp;

  @BeforeEach
  void setUp() {
    wodRepository.deleteAll();
    movementRepository.deleteAll();

    // Seed Movement (Required to link a WOD)
    pullUp = Movement.builder().id("GY-PU-001").name("Pull-up").category(Category.PULLING).build();
    movementRepository.save(pullUp);

    // Seed Initial WOD ("Fran")
    Wod fran =
        Wod.builder()
            .title("Fran")
            .wodType(WodType.FOR_TIME)
            .scoreType(ScoreType.TIME)
            .description("21-15-9 Thrusters and Pull-ups")
            .isPublic(true)
            .build();
    wodRepository.save(fran);
  }

  @AfterEach
  void cleanUpCache() {
    redisTemplate.execute(
        (RedisConnection connection) -> {
          connection.serverCommands().flushAll();
          return null;
        });
  }

  // -------------------------------------------------------------------------
  // GET Operations (Read)
  // -------------------------------------------------------------------------

  @Test
  @WithMockUser(username = "athlete")
  @DisplayName("GET /wods: should return list of summaries")
  void testGetAllWods_Success() throws Exception {
    mockMvc
        .perform(get("/aldebaran/wods"))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$", hasSize(1)))
        .andExpect(jsonPath("$[0].title").value("Fran"))
        .andExpect(jsonPath("$[0].wodType").value("FOR_TIME"));
  }

  @Test
  @WithMockUser(username = "athlete")
  @DisplayName("GET /wods/{id}: should return detailed WOD")
  void testGetWod_Success() throws Exception {
    // Retrieve the ID generated by DB
    Wod fran = wodRepository.findAll().get(0);

    mockMvc
        .perform(get("/aldebaran/wods/" + fran.getId()))
        .andExpect(status().isOk())
        .andExpect(jsonPath("$.title").value("Fran"))
        .andExpect(jsonPath("$.description").value("21-15-9 Thrusters and Pull-ups"));
  }

  @Test
  @WithMockUser(username = "athlete")
  @DisplayName("GET /wods/{id}: should return 404 for unknown ID")
  void testGetWod_NotFound() throws Exception {
    mockMvc
        .perform(get("/aldebaran/wods/99999"))
        .andExpect(status().isNotFound())
        .andExpect(jsonPath("$.title").value("Resource Not Found"));
  }

  // -------------------------------------------------------------------------
  // POST Operations (Create)
  // -------------------------------------------------------------------------

  @Test
  @WithMockUser(
      username = "coach",
      roles = {"COACH"})
  @DisplayName("POST /wods: should create WOD when Coach")
  void testCreateWod_AsCoach_Success() throws Exception {
    // Given
    WodRequest request =
        new WodRequest(
            "Murph",
            WodType.FOR_TIME,
            ScoreType.TIME,
            "Run 1 mile, 100 Pull-ups, 200 Push-ups, 300 Squats, Run 1 mile",
            "Wear a vest",
            true,
            3600, // Time cap
            0,
            0,
            "Chipper",
            List.of(
                // Link to the seeded movement
                new WodMovementRequest(
                    pullUp.getId(), 1, "100", 0.0, null, 0, null, 0.0, null, 0, null, null)));

    // When/Then
    mockMvc
        .perform(
            post("/aldebaran/wods")
                .with(csrf())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
        .andExpect(status().isCreated())
        .andExpect(jsonPath("$.title").value("Murph"))
        .andExpect(jsonPath("$.movements", hasSize(1)));

    // Verify Persistence
    assert (wodRepository.findAll().size() == 2); // Fran + Murph
  }

  @Test
  @WithMockUser(
      username = "user",
      roles = {"USER"})
  @DisplayName("POST /wods: should return 403 Forbidden when simple User")
  void testCreateWod_AsUser_Forbidden() throws Exception {
    WodRequest request =
        new WodRequest(
            "My Wod",
            WodType.AMRAP,
            ScoreType.ROUNDS_REPS,
            "Desc",
            null,
            false,
            600,
            0,
            0,
            null,
            List.of(
                new WodMovementRequest(
                    pullUp.getId(), 1, "10", 0.0, null, 0, null, 0.0, null, 0, null, null)));

    mockMvc
        .perform(
            post("/aldebaran/wods")
                .with(csrf())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
        .andExpect(status().isForbidden());
  }

  @Test
  @WithMockUser(
      username = "admin",
      roles = {"ADMIN"})
  @DisplayName("POST /wods: should return 404 if referencing unknown movement")
  void testCreateWod_UnknownMovement() throws Exception {
    // Given: Request referencing a non-existent movement ID
    WodRequest request =
        new WodRequest(
            "Impossible Wod",
            WodType.AMRAP,
            ScoreType.ROUNDS_REPS,
            "Desc",
            null,
            false,
            600,
            0,
            0,
            null,
            List.of(
                new WodMovementRequest(
                    "UNKNOWN-ID", 1, "10", 0.0, null, 0, null, 0.0, null, 0, null, null)));

    // When/Then
    mockMvc
        .perform(
            post("/aldebaran/wods")
                .with(csrf())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(request)))
        .andExpect(status().isNotFound())
        .andExpect(jsonPath("$.title").value("Resource Not Found"));
  }

  @Test
  @WithMockUser(
      username = "admin",
      roles = {"ADMIN"})
  @DisplayName("POST /wods: should return 400 Bad Request on Validation Error")
  void testCreateWod_ValidationFailure() throws Exception {
    // Given: Invalid request (Empty Title)
    WodRequest invalidRequest =
        new WodRequest(
            "", // @NotBlank failure
            WodType.AMRAP,
            ScoreType.ROUNDS_REPS,
            "Desc",
            null,
            false,
            600,
            0,
            0,
            null,
            Collections.emptyList());

    mockMvc
        .perform(
            post("/aldebaran/wods")
                .with(csrf())
                .contentType(MediaType.APPLICATION_JSON)
                .content(objectMapper.writeValueAsString(invalidRequest)))
        .andExpect(status().isBadRequest())
        .andExpect(jsonPath("$.title").value("Validation Error"));
  }
}
