package apex.stellar.antares.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Objects;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * Represents a Tenant in the system, which can be a physical Gym (Box) or a virtual Programming
 * Track.
 *
 * <p>This entity acts as the root context for Memberships and domain data. Equality is based on the
 * unique {@code name}.
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name = "gyms")
@EntityListeners(AuditingEntityListener.class)
public class Gym implements Serializable {

  @Serial private static final long serialVersionUID = 1L;

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /** The unique display name of the Gym or Programming track. Business Key. */
  @Column(nullable = false, unique = true)
  private String name;

  /** A brief description of the facility or program. */
  @Column(columnDefinition = "TEXT")
  private String description;

  /**
   * The code required for users to join this Gym.
   *
   * <p>Generated by the system and modifiable by Gym Admins.
   */
  @Column(name = "enrollment_code")
  private String enrollmentCode;

  /**
   * Flag indicating the type of facility.
   *
   * <ul>
   *   <li>{@code true}: Virtual Programming (Remote coaching).
   *   <li>{@code false}: Physical CrossFit Box.
   * </ul>
   */
  @Column(name = "is_programming", nullable = false)
  private boolean isProgramming;

  /**
   * Configuration flag for membership approval.
   *
   * <ul>
   *   <li>{@code true}: Users become {@code ACTIVE} immediately upon joining.
   *   <li>{@code false}: Users join as {@code PENDING} and require staff validation.
   * </ul>
   */
  @Column(name = "is_auto_subscription", nullable = false)
  private boolean isAutoSubscription;

  /** The lifecycle status of the Gym (e.g., pending admin approval). */
  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  @Builder.Default
  private GymStatus status = GymStatus.PENDING_APPROVAL;

  @CreatedDate
  @Column(name = "created_at", nullable = false, updatable = false)
  private LocalDateTime createdAt;

  @LastModifiedDate
  @Column(name = "updated_at", nullable = false)
  private LocalDateTime updatedAt;

  // --- Effective Java: Equals & HashCode based on Business Key (Name) ---

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Gym gym = (Gym) o;
    return Objects.equals(name, gym.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name);
  }

  @Override
  public String toString() {
    return "Gym{"
        + "id="
        + id
        + ", name='"
        + name
        + '\''
        + ", status="
        + status
        + ", isProgramming="
        + isProgramming
        + '}';
  }

  /** Enumeration tracking the lifecycle of a Gym entity. */
  public enum GymStatus {
    PENDING_APPROVAL,
    ACTIVE,
    REJECTED,
    SUSPENDED
  }
}
