-- 1. Create Gyms Table
CREATE TABLE gyms
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(255) NOT NULL UNIQUE,
    description          TEXT,
    enrollment_code      VARCHAR(50),
    is_programming       BOOLEAN      NOT NULL DEFAULT FALSE,
    is_auto_subscription BOOLEAN      NOT NULL DEFAULT FALSE,
    status               VARCHAR(50)  NOT NULL DEFAULT 'PENDING_APPROVAL',
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Create Memberships Table
CREATE TABLE memberships
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    gym_id     BIGINT      NOT NULL,
    gym_role   VARCHAR(50) NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT fk_memberships_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_memberships_gym FOREIGN KEY (gym_id) REFERENCES gyms (id) ON DELETE CASCADE,
    CONSTRAINT uq_memberships_user_gym UNIQUE (user_id, gym_id),
    CONSTRAINT chk_gym_role CHECK (gym_role IN ('OWNER', 'PROGRAMMER', 'COACH', 'ATHLETE'))
);

-- 3. Create Permissions Table (ElementCollection)
CREATE TABLE membership_permissions
(
    membership_id BIGINT      NOT NULL,
    permission    VARCHAR(50) NOT NULL,

    -- Constraints
    CONSTRAINT fk_membership_permissions_membership FOREIGN KEY (membership_id) REFERENCES memberships (id) ON DELETE CASCADE,
    -- Composite Primary Key to ensure uniqueness (Set semantic) and index speed
    PRIMARY KEY (membership_id, permission)
);

-- 4. Indexes for Performance
CREATE INDEX idx_memberships_user_id ON memberships (user_id);
CREATE INDEX idx_memberships_gym_id ON memberships (gym_id);
CREATE INDEX idx_gyms_name ON gyms (name);